/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/milestones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get baby wear milestones
         * @description Returns a list of recommended baby wear items for each month from birth to 2 years old.
         */
        get: operations["getMilestones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Item: {
            /**
             * @description Universal name of the item (e.g., combi-hadagi)
             * @example コンビ肌着
             */
            universal_name: string;
            /**
             * @description Shop-specific name of the item
             * @example コットンフライスコンビ肌着
             */
            shop_specific_name: string;
            /** @description Category label for display */
            category_label: string;
            /** @description Emoji represention of the category */
            category_emoji: string;
            /** @description Background color for item icon */
            category_color: string;
        };
        Milestone: {
            /**
             * @description Age in months at this milestone
             * @example 0
             */
            age_in_months: number;
            /**
             * Format: date
             * @description The date corresponding to this milestone
             * @example 2023-10-01
             */
            target_date: string;
            /**
             * @description Estimated clothing size in cm
             * @example 50-60cm
             */
            size: string;
            /** @description List of recommended items */
            items: components["schemas"]["Item"][];
        };
        MilestoneResponse: {
            /** @description List of milestones from birth to 24 months */
            milestones: components["schemas"]["Milestone"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMilestones: {
        parameters: {
            query: {
                /** @description Baby's birth date (YYYY-MM-DD) */
                birth_date: string;
                /** @description Target shop name for specific terminology (e.g., uniqlo, nishimatsuya, akachan_honpo) */
                target_shop?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful milestones response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MilestoneResponse"];
                };
            };
            /** @description Invalid input parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
