// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package handler

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// GetRecommendationParams defines parameters for GetRecommendation.
type GetRecommendationParams struct {
	// BirthDate Baby's birth date (YYYY-MM-DD)
	BirthDate openapi_types.Date `form:"birth_date" json:"birth_date"`

	// TargetShop Target shop name for specific terminology (e.g., uniqlo, nishimatsuya, akachan_honpo)
	TargetShop *string `form:"target_shop,omitempty" json:"target_shop,omitempty"`

	// CurrentTemp Current temperature in degrees Celsius
	CurrentTemp float32 `form:"current_temp" json:"current_temp"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get recommended baby wear
	// (GET /recommend)
	GetRecommendation(c *gin.Context, params GetRecommendationParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetRecommendation operation middleware
func (siw *ServerInterfaceWrapper) GetRecommendation(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRecommendationParams

	// ------------- Required query parameter "birth_date" -------------

	if paramValue := c.Query("birth_date"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument birth_date is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "birth_date", c.Request.URL.Query(), &params.BirthDate)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter birth_date: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "target_shop" -------------

	err = runtime.BindQueryParameter("form", true, false, "target_shop", c.Request.URL.Query(), &params.TargetShop)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter target_shop: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "current_temp" -------------

	if paramValue := c.Query("current_temp"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument current_temp is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "current_temp", c.Request.URL.Query(), &params.CurrentTemp)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter current_temp: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRecommendation(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/recommend", wrapper.GetRecommendation)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/4xUTWscRxD9K01dYkPvaiTZYObmDwgCG4zjEIQRS+1M7Uw7M92t7mo5i1gI2ksOuYUc",
	"c8slZ53ye+aQ/IzQPfsx2lkFn4bprnr1XtXrugWlFwbyWyjJF05ZVkZDDi/fX4iFccJRYdqWdKl0JeY4",
	"X4ovhE7M0VMpjBZz5bgWJTIJ1KVgai055OBIii+Ka+FrYyfeUqEWqhAaW/JTkMCKG4IcXkXIHyLkR4fa",
	"N8jGiZfvL0DCDTnfkzmdZtMMVhKMJY1WQQ7n02x6DhIscu0j/ZMd0/hXEY81fSAOTnuBolGehVns1VE5",
	"EKeYWr+XyDWly2+8wKqXWQTnSPNQbhRl0o8y+qKEHL4l/rDFT6eJrsOWmJyH/NMhv1d9kUFLn1xeXl5O",
	"3r2bvHnzFCSoGHUdyC1BQmwl5JCiZzEaJDi6DspRCTm7QBJ8UVOLsRP0E7Y2dfwsOzufnGaT7BQkLIxr",
	"kSGHDQAvbYzx7JSuYLWShxw/oquI01TTMJNJduNlcq3SpjHVUjyhaTWVImh13RgptPK1apF9WKIU+CMW",
	"NepZbbQ1j0njVGsWa8FxLT341/B+PZ6YUFqUVDkiL15T41XwjxDZjHsWk7+uy6fPp88H3V00BnlPU4d2",
	"Tg5Wq6sI5q3RnpKJz7IsfgqjmXRyMFrbqCLZ5+Szj1JuB/Wsi5Zj1WdjRTOlZ63Rmzdx0AJsitAgU5l8",
	"rLTYRMo972c7jkozVZGkhPQexnhvjzyiPnSQ8pBhHOVs65ZZ391D2O9GCyMWiY8wgg7JQnd3363X3fqX",
	"bn3frX/v1n91d392d3+n8/tu/du/d7/+88fPY3/I6Jy4X7B5hMX32/sRg62xC9PO1aTGEiv1dEzr/8qv",
	"hh76dMhFHmvT1Q7EzD9TwVHD5gCdw+UI9KEZthMZw8S8gwGEoiDvF6HZjzYZUGy9Gos/6636MPVC32Cj",
	"SqG0DSwGyy5W8aFt0S37zXh89fZ0PLmb4xvyrSmwEf09SAiugRxqZpufnDTxrjae8xfZiwxWV6v/AgAA",
	"///XUfto3AYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
