/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recommended baby wear
         * @description Returns a list of recommended baby wear items based on the baby's age and current temperature.
         */
        get: operations["getRecommendation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Item: {
            /**
             * @description Universal name of the item (e.g., combi-hadagi)
             * @example コンビ肌着
             */
            universal_name: string;
            /**
             * @description Shop-specific name of the item
             * @example コットンフライスコンビ肌着
             */
            shop_specific_name: string;
        };
        RecommendationResponse: {
            /**
             * @description Calculated age in months
             * @example 4
             */
            age_in_months: number;
            /** @description List of recommended items */
            items: components["schemas"]["Item"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getRecommendation: {
        parameters: {
            query: {
                /** @description Baby's birth date (YYYY-MM-DD) */
                birth_date: string;
                /** @description Target shop name for specific terminology (e.g., uniqlo, nishimatsuya, akachan_honpo) */
                target_shop?: string;
                /** @description Target date to wear the baby wear (YYYY-MM-DD), defaults to today */
                target_date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful recommendation response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Invalid input parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
